In [9]:
# Import Dependencies

import geopy
import pandas as pd

In [10]:
# Make Listings Data from AirBnB a DataFrame

listings_df = pd.read_csv("Revised_Columbus_Listings.csv", index_col=0)

In [11]:
# Show DataFrame

listings_df

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
id,,,,,,,,,,,,,,,,,
9.067600e+04,Short North - Italianate Cottage,483306,Audra & Lacey,NaN,Near North/University,39.983940,-83.003210,Entire home/apt,213,1,605,9/11/22,4.54,3,161,110,2022-2475
5.431400e+05,Private queen bedroom 1 - N.Campus,2350409,Edward,NaN,Near North/University,40.012430,-83.009860,Private room,29,3,123,8/29/22,1.00,3,263,16,2019-1344
5.911010e+05,The Bellows' Studio Loft (3rd floor apartment),2889677,Gail,NaN,Near East,39.960860,-82.979680,Private room,100,2,272,9/18/22,2.21,1,353,30,2019-1230
9.232480e+05,1 Single Bed in a Shared Coed Dorm at the Hostel,4965048,Mathew,NaN,Near North/University,40.012590,-83.001640,Shared room,37,1,286,9/4/22,2.45,9,359,45,2019-1314
9.278670e+05,Full Private Room at the Hostel,4965048,Mathew,NaN,Near North/University,40.012590,-83.001640,Private room,72,1,63,6/19/22,0.57,9,352,7,2019-1314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7.190000e+17,"Charming 3 Bedroom Home, Steps from Short North!",478727368,Lisas Team,NaN,Near North/University,39.979890,-83.001570,Entire home/apt,53,1,0,NaN,NaN,14,23,0,2021-6642
7.190000e+17,Private Home away from Home close to Schiller ...,478727368,Lisas Team,NaN,Near South,39.943780,-82.984220,Entire home/apt,75,1,0,NaN,NaN,14,54,0,2022-1940
7.200000e+17,The Top-Floor 1BR Penthouseâ€”Downtown Columbus,116400313,Nate,NaN,Downtown,39.964276,-82.997779,Entire home/apt,75,30,0,NaN,NaN,25,110,0,NaN
7.200000e+17,"*Cameron Room* Cozy, Close to OSU, Downtown, etc",217660325,Jin,NaN,Near North/University,40.008060,-83.002470,Private room,118,2,0,NaN,NaN,53,86,0,2022-2930
7.200000e+17,"*Clara Room* Spacious, Close to OSU, Downtown,...",217660325,Jin,NaN,Near North/University,40.005850,-83.001270,Private room,52,2,0,NaN,NaN,53,19,0,2022-2930

In [12]:
# Start Geolocator from GeoPY

geolocator = geopy.Nominatim(user_agent="kar")

In [13]:
# Function to Retrieve Zip from Latitude and Longitude Coordinates in Listings DataFrame

def get_zip_code(x):
    location = geolocator.reverse("{}, {}".format(x['latitude'],x['longitude']))
    return location.raw['address']['postcode']

listings_df['zipcode'] = listings_df.apply(lambda x: get_zip_code(x), axis = 1)

In [14]:
# Show Listings DataFrame with Zip 

listings_df

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,zipcode
id,,,,,,,,,,,,,,,,,,
9.067600e+04,Short North - Italianate Cottage,483306,Audra & Lacey,NaN,Near North/University,39.983940,-83.003210,Entire home/apt,213,1,605,9/11/22,4.54,3,161,110,2022-2475,43201
5.431400e+05,Private queen bedroom 1 - N.Campus,2350409,Edward,NaN,Near North/University,40.012430,-83.009860,Private room,29,3,123,8/29/22,1.00,3,263,16,2019-1344,43202
5.911010e+05,The Bellows' Studio Loft (3rd floor apartment),2889677,Gail,NaN,Near East,39.960860,-82.979680,Private room,100,2,272,9/18/22,2.21,1,353,30,2019-1230,43205
9.232480e+05,1 Single Bed in a Shared Coed Dorm at the Hostel,4965048,Mathew,NaN,Near North/University,40.012590,-83.001640,Shared room,37,1,286,9/4/22,2.45,9,359,45,2019-1314,43202
9.278670e+05,Full Private Room at the Hostel,4965048,Mathew,NaN,Near North/University,40.012590,-83.001640,Private room,72,1,63,6/19/22,0.57,9,352,7,2019-1314,43202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7.190000e+17,"Charming 3 Bedroom Home, Steps from Short North!",478727368,Lisas Team,NaN,Near North/University,39.979890,-83.001570,Entire home/apt,53,1,0,NaN,NaN,14,23,0,2021-6642,43215
7.190000e+17,Private Home away from Home close to Schiller ...,478727368,Lisas Team,NaN,Near South,39.943780,-82.984220,Entire home/apt,75,1,0,NaN,NaN,14,54,0,2022-1940,43206
7.200000e+17,The Top-Floor 1BR Penthouseâ€”Downtown Columbus,116400313,Nate,NaN,Downtown,39.964276,-82.997779,Entire home/apt,75,30,0,NaN,NaN,25,110,0,NaN,43215
7.200000e+17,"*Cameron Room* Cozy, Close to OSU, Downtown, etc",217660325,Jin,NaN,Near North/University,40.008060,-83.002470,Private room,118,2,0,NaN,NaN,53,86,0,2022-2930,43201
7.200000e+17,"*Clara Room* Spacious, Close to OSU, Downtown,...",217660325,Jin,NaN,Near North/University,40.005850,-83.001270,Private room,52,2,0,NaN,NaN,53,19,0,2022-2930,43201

In [15]:
# Export Dataframe as .csv File 

listings_df.to_csv('Revised_Columbus_Listings_with_Zip.csv')

In [18]:
# Create dependencies for SQL Alchemy

from sqlalchemy import create_engine
from config import db_password

In [19]:
# Add the information to send the data to PostgresSQL
    
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5433/Air_BnB"
    
engine = create_engine(db_string)
    
listings_df.to_sql(name="listings", con=engine)

197