In [5]:
# Create dependencies

import pandas as pd
from sqlalchemy import create_engine
from config import db_password

In [2]:
# Bring in Listings from Get_Zip file

listings_df = pd.read_csv('Columbus_listings_with_Zip.csv')
listings_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,zipcode
0,90676,Short North - Italianate Cottage,483306,Audra & Lacey,NaN,Near North/University,39.983940,-83.003210,Entire home/apt,213,1,605,2022-09-11,4.54,3,161,110,2022-2475,43201.0
1,543140,Private queen bedroom 1 - N.Campus,2350409,Edward,NaN,Near North/University,40.012430,-83.009860,Private room,29,3,123,2022-08-29,1.00,3,263,16,2019-1344,43202.0
2,591101,The Bellows' Studio Loft (3rd floor apartment),2889677,Gail,NaN,Near East,39.960860,-82.979680,Private room,100,2,272,2022-09-18,2.21,1,353,30,2019-1230,43205.0
3,923248,1 Single Bed in a Shared Coed Dorm at the Hostel,4965048,Mathew,NaN,Near North/University,40.012590,-83.001640,Shared room,37,1,286,2022-09-04,2.45,9,359,45,2019-1314,43202.0
4,927867,Full Private Room at the Hostel,4965048,Mathew,NaN,Near North/University,40.012590,-83.001640,Private room,72,1,63,2022-06-19,0.57,9,352,7,2019-1314,43202.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,719459298609982363,"Charming 3 Bedroom Home, Steps from Short North!",478727368,Lisas Team,NaN,Near North/University,39.979890,-83.001570,Entire home/apt,75,1,0,NaN,NaN,14,23,0,2021-6642,43215.0
2193,719462438891781706,Private Home away from Home close to Schiller ...,478727368,Lisas Team,NaN,Near South,39.943780,-82.984220,Entire home/apt,75,1,0,NaN,NaN,14,54,0,2022-1940,43206.0
2194,719758428460095764,The Top-Floor 1BR Penthouseâ€”Downtown Columbus,116400313,Nate,NaN,Downtown,39.964276,-82.997779,Entire home/apt,118,30,0,NaN,NaN,25,110,0,NaN,43215.0
2195,719760392721789064,"*Cameron Room* Cozy, Close to OSU, Downtown, etc",217660325,Jin,NaN,Near North/University,40.008060,-83.002470,Private room,52,2,0,NaN,NaN,53,86,0,2022-2930,43201.0
2196,719765833016581493,"*Clara Room* Spacious, Close to OSU, Downtown,...",217660325,Jin,NaN,Near North/University,40.005850,-83.001270,Private room,51,2,0,NaN,NaN,53,19,0,2022-2930,43201.0

In [10]:
# Add the information to send the data to PostgresSQL
    
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5433/Columbus_AirBnB"
    
engine = create_engine(db_string)
    
listings_df.to_sql(name="listings", con=engine)

197